[package]
name = "rusty"
version = "0.1.0"
authors = []

[lib]
name = "rusty"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.15.1"
rustler_codegen = {git = "https://github.com/evnu/rustler", branch = "decode-record"}
lazy_static = "0.2"
